# Generated by Django 3.1.3 on 2020-11-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readtext', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='newsHeading',
            field=models.CharField(max_length=1000),
        ),
    ]
